variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
  GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository
image: maven:latest

stages:
    - build
    - test
    - package
    - sonar
    - deploy
cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
      - .m2/repository
      - target

build_job:
  stage: build
  tags:
    - awsgitrunner 

  script: 
    - echo "Maven compile started"
    - "mvn compile"
    
test_job:
  stage: test
  tags:
    - awsgitrunner 

  script: 
    - echo "Maven test started"
    - "mvn test"

package_job:
  stage: package
  tags:
    - awsgitrunner 

  script: 
    - echo "Maven packaging started"
    - "mvn package"

sonarcloud-check:
  stage: sonar
 #image: maven:3.6.3-jdk-11
  script:
    - mvn verify sonar:sonar -Dsonar.projectKey=madhavadakula_gitlabcicd
  
